### ISSUE TITLE
Issue with Numpy 1.24

### ISSUE THREAD

**Issue by asmasca** [hpparvi/PyTransit#152]
When trying to run pytransit along with numpy 1.24, I get the error:

"ImportError: cannot import name 'int' from 'numpy'"

It works fine with numpy 1.23.

**Comment by hpparvi** [comment]
Fixed now in the latest version.
